---

- name: Copy FireEye Agent Config
  copy:
    src: "{{ fireeye_agent_config_local_dir }}/{{ fireeye_agent_config_vault }}"
    dest: "{{ fireeye_agent_install_path }}/{{ fireeye_agent_config }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 
    - Import fireeye config
    - Restart fireeye agent
